wizzlern_pegi.settings:
  type: config_object
  mapping:
    games_page_title:
      type: label
      label: 'Games page title'
    games_per_page:
      type: integer
      label: 'Games per page'

block.settings.wizzlern_pegi_new_games:
  type: block_settings
  mapping:
    max_items:
      type: integer
      label: 'Number of games'
